language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install flake8
  - npm install eslint eslint-plugin-import eslint-config-airbnb-base
script:
  - flake8
  - ./node_modules/.bin/eslint **/*.js
